services:
  - type: web
    name: comp3011-cw1-api
    runtime: python
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: comp3011-cw1-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://comp3011-cw1-api.onrender.com,http://localhost:8000
      - key: RATE_LIMIT_ENABLED
        value: "true"

databases:
  - name: comp3011-cw1-db
    databaseName: comp3011
    user: comp3011
    plan: free
